* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}

** Exporter Settings
#+AUTHOR: Valentin Musoiu
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Valentin Mușoiu}
\photoR{2.8cm}{vali_2023.jpeg}
\tagline{Software engineer}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \email{valentin.musoiu@gmail.com}
  \location{Ploiești, RO}
  \github{iqltd}
  \linkedin{iqltd}
  \dob{25 November 1987}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Personal Statement Default :ignore:
#+begin_export latex
 \begin{quote}
 ``Software engineer with an extensive experience and a healthy amount of self-doubt''
 \end{quote}
#+end_export

** Experience
*** EMQ :ignore:
{{{cvevent(Backend engineer, EMQ Inc., July 2017 -- Ongoing, Taipei\, TW/Remote)}}}

Building and maintaining a resilient backend for a fast-growing international remittance company.

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

Things I am proud of:
- The resilience of our product (I witnessed 100-fold growth in traffic with no notable downtimes)
- Maturing into a polyglot programmer (writing code in Erlang, Python, Go, JavaScript)
- Being the first remote developer in the company (creating the path for the others who followed)
- Taking my productivity to the next level with Emacs.

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

Notable projects:
- maintenance and evolution of the ledger system and integration with external accounting system
- design and implementation of a live balance subsystem and profit and loss projection report for the treasury team
- triggering payments from Facebook messenger


#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

{{{cvtag(Erlang)}}}
{{{cvtag(Python)}}}
{{{cvtag(Flask)}}}
{{{cvtag(Django)}}}
{{{cvtag(FastAPI)}}}
{{{cvtag(SQLAlchemy)}}}
{{{cvtag(Go)}}}
{{{cvtag(JavaScript)}}}
{{{cvtag(React)}}}
{{{cvtag(PostgreSQL)}}}
{{{cvtag(Docker)}}}
{{{cvtag(AWS)}}}

*** Commerz Systems GmbH :ignore:
{{{par-div}}}
{{{cvevent(Software Engineer, Commerz Systems GmbH, May 2016 -- Jan 2017, Prague\, CZ)}}}

Development, in a Scrum team, of a workflow-based application for the account opening process used inside Germany’s second largest bank.

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

Things I am proud of:

- Swift ramp-up, managing to become a respected contributor to the team in the first month
- Implementing a configuration-driven business rule engine
- Contributing SoapUI projects to streamline manual testing on the staging platform for devs

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

Projects:
- Front End and Back End development
- Integration with internal systems
- Integration with 3rd party AML service

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

{{{cvtag(Java)}}}
{{{cvtag(JSF)}}}
{{{cvtag(Javascript)}}}
{{{cvtag(Spring Boot)}}}
{{{cvtag(Hibernate)}}}
{{{cvtag(Oracle DB)}}}
{{{cvtag(Tomcat)}}}
{{{cvtag(Websphere)}}}


** Newpage :ignore:
{{{new-page}}}

** Experience (Cont.)
*** Gemalto :ignore:
{{{cvevent(Software Engineer, Gemalto (now Thales), July 2014 -- Apr 2016, Prague\, CZ)}}}

I worked on several Telco projects, in close collaboration with teams from France, the Americas and Asia.

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

Things I am proud of:

- Building a continuous integration infrastructure for our application.
- Informally leading a team of 4 for a 3-months project.
- Building the back end for a service with 85%+ test coverage.
- Kept my sanity after working on a project where bash was used as a programming language.

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

Notable projects:
- Customization of the flagship OTA (Over-the-Air) subscription management platform for one of the global Telco leaders
- Customization of a solution for Mobile Network Operators (written in PHP, C and bash) for worlwide customers

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

{{{cvtag(Java)}}}
{{{cvtag(JSF)}}}
{{{cvtag(EJB)}}}
{{{cvtag(JPA)}}}
{{{cvtag(Oracle DB)}}}
{{{cvtag(MySQL)}}}
{{{cvtag(Weblogic)}}}
{{{cvtag(bash)}}}
{{{cvtag(C)}}}
{{{cvtag(PHP)}}}
{{{cvtag(MySQL)}}}

*** IBM Romania :ignore:
{{{par-div}}}

{{{cvevent(Application Developer, IBM Global Delivery Center Eastern Europe, July 2008 -- June 2014, Bucharest\, RO)}}}

I worked on several banking projects, in close collaboration with functional analysts from Western Europe.

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

Things I am proud of:

- Growing from an intern to a lead developer.
- Transitioning to Java development from COBOL development.
- Contributing to the implementation of CMMI level 5 processes on our team.

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

Notable projects:
- maintenance of a core banking software solution (written in COBOL) used by several European banks
- development of a core banking software solution in Java for a large Italian bank
- development of a workflow-based solution for a leading German bank

#+BEGIN_EXPORT latex
\smallskip
#+END_EXPORT

{{{cvtag(Java)}}}
{{{cvtag(JSF)}}}
{{{cvtag(EJB)}}}
{{{cvtag(JPA)}}}
{{{cvtag(COBOL)}}}
{{{cvtag(DB2)}}}
{{{cvtag(Oracle DB)}}}
{{{cvtag(iSeries)}}}
{{{cvtag(Oracle BPM)}}}

** An Average Sprint
#+begin_export latex
% % Adapted from @Jake's answer from http://tex.stackexchange.com/a/82729/226
% % comma-separated list of value/text width/color/detail}
\wheelchart{1.5cm}{0.5cm}{%
   5/10em/accent!10/{Meetings, planning},
   30/8em/accent!40/{Requirements gathering, design, documentation},
   10/8em/accent!20/{Investigations, support},
   50/8em/accent!50/{Coding, deploying, testing},
   5/6em/accent!30/{Learning, experimenting}
 }
#+end_export

** Newpage :ignore:noexport:
{{{new-page}}}

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export
** Skills
{{{cvtag(Erlang)}}}
{{{cvtag(Python)}}}
{{{cvtag(Go)}}}
{{{cvtag(Java)}}}
{{{cvtag(COBOL)}}}

{{{divider}}}

{{{cvtag(PostgreSQL)}}}
{{{cvtag(Docker)}}}
{{{cvtag(AWS)}}}

{{{divider}}}

{{{cvtag(Git)}}}
{{{cvtag(Emacs)}}}
{{{cvtag(bash)}}}
{{{cvtag(tmux)}}}


** Skills erlang :noexport:
{{{cvtag(Erlang/OTP)}}}
{{{cvtag(Cowboy)}}}
{{{cvtag(Python)}}}
{{{cvtag(Java)}}}
{{{cvtag(Go)}}}
{{{cvtag(COBOL)}}}

{{{divider}}}

{{{cvtag(PostgreSQL)}}}
{{{cvtag(Docker)}}}
{{{cvtag(AWS)}}}

{{{divider}}}

{{{cvtag(Git)}}}
{{{cvtag(Emacs)}}}
{{{cvtag(bash)}}}
{{{cvtag(tmux)}}}


** Skills python :noexport:
{{{cvtag(Python)}}}
{{{cvtag(FastAPI)}}}
{{{cvtag(SQLAlchemy)}}}
{{{cvtag(Erlang)}}}
{{{cvtag(Java)}}}
{{{cvtag(Go)}}}
{{{cvtag(COBOL)}}}

{{{divider}}}

{{{cvtag(PostgreSQL)}}}
{{{cvtag(Docker)}}}
{{{cvtag(AWS)}}}

{{{divider}}}

{{{cvtag(Git)}}}
{{{cvtag(Emacs)}}}
{{{cvtag(bash)}}}
{{{cvtag(tmux)}}}


** Skills java :noexport:
{{{cvtag(Java/Java EE)}}}
{{{cvtag(Python)}}}
{{{cvtag(Erlang)}}}
{{{cvtag(Go)}}}
{{{cvtag(COBOL)}}}

{{{divider}}}

{{{cvtag(PostgreSQL)}}}
{{{cvtag(Docker)}}}
{{{cvtag(AWS)}}}

{{{divider}}}

{{{cvtag(Git)}}}
{{{cvtag(Emacs)}}}
{{{cvtag(bash)}}}
{{{cvtag(tmux)}}}


** Education

{{{cvevent(MS Economic Informatics, University of Economic Studies Bucharest, Oct 2009 - July 2011,)}}}

{{{divider}}}

{{{cvevent(BS Economic Cybernetics, University of Economic Studies Bucharest, Oct 2006 - July 2009,)}}}


** Certifications java :noexport:

{{{cvevent(Oracle Certified Expert, Java EE 6 Entreprise JavaBeans Developer, Dec 2012 )}}}

{{{divider}}}

{{{cvevent(Oracle Certified Expert, Java EE 6 Java Server Pages and Servlets Developer, Dec 2011 )}}}

{{{divider}}}

{{{cvevent(Oracle Certified Professional Java Programmer for SE 6.0, Sep 2010 )}}}


** Philosophy
#+begin_export latex
\medskip
\begin{quote}
 ``Simple is better than complex.''
\end{quote}
\bigskip
#+end_export

** Languages :ignore:
#+begin_export latex
\cvsection{Languages}

\cvskill{English}{5}
\divider

\cvskill{Italian}{3}
\divider

\cvskill{French}{2}
\divider

\cvskill{Romanian}{5}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \medskip
#+end_export

\newpage


** Newpage :ignore:
#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT


** Most Proud Of
{{{cvachievement(\faUsers, Team player, Established myself as a confident\, enthusiastic and effective team member\, having experience leading as well as following.)}}}

{{{divider}}}

{{{cvachievement(\faBook, Polyglot programmer, Comfortable writing code in different programming languages\, understanding that each has its own merits\, especially by casting a new light on the problems.)}}}

{{{divider}}}

{{{cvachievement(\faTerminal, Touch typer, Using the mouse less and less\, leveraging the productivity offered by the terminal\, Emacs and my Moonlander split keyboard.)}}}

{{{divider}}}

{{{cvachievement(\faGlobe, Cosmopolitan, Lived on 3 continents and worked with people from 5 continents.)}}}

{{{divider}}}

{{{cvachievement(\faChild, Daddy, Having my mind blown away everyday by a sweet curious and very inquisitive little boy I have the pleasure of calling "son".)}}}

{{{divider}}}

{{{cvachievement(\faFilm, Hobbyist film-maker, Director and/or editor of several amateur short film productions\, including the recipient of the Jameson Done in 60 Seconds first prize for the Romanian stage in 2012.)}}}


* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export



